
#spring.profiles.active: local
server:
  port: 80
  http:
    protocol-version: HTTP/1.1
  #ssl:
  #  enabled: true # Uses self-signed certificate because no key-store configuration is specified.

security:
  jwt:
    ttlMillis: '604800000'
    issuer: Main
    secret: ghk45jgherogho834go3h4gefkhjuvhbsdhbhhef565648941


internal.lb.uri: http://localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: enrollment
          uri: ${internal.lb.uri}:9000
          predicates:
            - Path=/api/v1/enrollments/**
          filters:
            - AuthenticationFilter
        - id: approvedCourses
          uri: ${internal.lb.uri}:9001
          predicates:
            - Path=/api/v1/approvedCourses/**
          filters:
            - AuthenticationFilter
        - id: courses
          uri: ${internal.lb.uri}:9002
          predicates:
            - Path=/api/v1/courses/**
          filters:
            - AuthenticationFilter
        - id: prerequisites
          uri: ${internal.lb.uri}:9003
          predicates:
            - Path=/api/v1/prerequisites/**
          filters:
            - AuthenticationFilter
        - id: teachers
          uri: ${internal.lb.uri}:9004
          predicates:
            - Path=/api/v1/teachers/**
          filters:
            - AuthenticationFilter
        - id: students
          uri: ${internal.lb.uri}:9005
          predicates:
            - Path=/api/v1/students/**
          filters:
            - AuthenticationFilter
        - id: user
          uri: ${internal.lb.uri}:9008
          predicates:
            - Path=/api/v1/user/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}