
#spring.profiles.active: local
server:
  port: 80
  http:
    protocol-version: HTTP/1.1
  #ssl:
  #  enabled: true # Uses self-signed certificate because no key-store configuration is specified.

security:
  jwt:
    ttlMillis: '604800000'
    issuer: Main
    secret: ghk45jgherogho834go3h4gefkhjuvhbsdhbhhef565648941


internal.lb.uri: http://localhost
spring:
  cloud:
    gateway:
      globalcors:
        #add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*" # Add your allowed origin
            allowedMethods:
              - 'GET'
              - 'POST'
              - 'PUT'
              - 'DELETE'
              - 'OPTIONS'
              - 'HEAD'
            allowedHeaders:
              - 'origin'
              - 'content-type'
              - 'accept'
              - 'authorization'
              - 'cookie'
      discovery:
        locator:
          enabled: true
      routes:
        - id: enrollment
          uri: https://enrollment-service-sophosuni.onrender.com
          predicates:
            - Path=/api/v1/enrollments/**
          filters:
            - AuthenticationFilter
        - id: approvedCourses
          uri: https://historyapproved-service-sophosuni.onrender.com
          predicates:
            - Path=/api/v1/approvedCourses/**
          filters:
            - AuthenticationFilter
        - id: courses
          uri: https://course-service-sophosuni.onrender.com
          predicates:
            - Path=/api/v1/courses/**
          filters:
            - AuthenticationFilter
        - id: prerequisites
          uri: https://prerequisites-service-sophosuni.onrender.com
          predicates:
            - Path=/api/v1/prerequisites/**
          filters:
            - AuthenticationFilter
        - id: teachers
          uri: https://teacher-service-sophosuni.onrender.com
          predicates:
            - Path=/api/v1/teachers/**
          filters:
            - AuthenticationFilter
        - id: students
          uri: https://student-servicesophosuni.onrender.com
          predicates:
            - Path=/api/v1/students/**
          filters:
            - AuthenticationFilter
        - id: user
          uri: https://user-service-try.onrender.com
          predicates:
            - Path=/api/v1/user/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}